# -- Site Configuration --
# PaperMod: https://github.com/adityatelange/hugo-PaperMod

theme = "PaperMod"
baseURL = "https://classroom.anir0y.in/"
defaultContentLanguage = "en"
title = "Classroom"

enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[minify]
  disableXML = true
  minifyOutput = true
