# -- Main Menu --

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 10

[[main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 30

[[main]]
  name = "Archives"
  url = "/archives/"
  weight = 40

[[main]]
  name = "Search"
  url = "/search/"
  weight = 50

[[main]]
  name = "About"
  url = "/about/me/"
  weight = 60
